apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: ls-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-website
  labels:
    app: ls-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ls-website
  template:
    metadata:
      labels:
        app: ls-website
    spec:
      containers:
      - name: ls-website
        image: website
        ports:
        - containerPort: 80


